In [1]:
import pandas as pd

file_path = '../test.xlsx'

go_data = pd.read_excel(file_path, sheet_name='출근')
leave_data = pd.read_excel(file_path, sheet_name='퇴근')

In [2]:
go_data.head()

,탑승 일시,탑승 시간,교통수단,사용처,사용금액,사용후잔액,승차역,하차역,하차일시,하차 시간,노선(호선),차량번호
0,2023-05-31,07:56:26,버스,(주)서울승합,400원,"27,550원",신논현역.구교보타워사거리,학동역5번출구,2023-05-31,08:03:11,3412번(강동공영차고지~강남역),서울74사4220
1,2023-05-31,06:51:06,버스,경남여객(노선입찰제),"2,800원","27,950원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-05-31,07:53:30,경기버스노선,NaN
2,2023-05-30,07:52:41,버스,경기상운(노선입찰제),300원,"34,350원",지하철2호선.강남역(중),학동역6번출구,2023-05-30,08:05:21,경기버스노선,NaN
3,2023-05-30,06:36:58,버스,경남여객(노선입찰제),"2,800원","34,650원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-05-30,07:45:09,경기버스노선,NaN
4,2023-05-31,07:56:26,버스,(주)서울승합,400원,"27,550원",신논현역.구교보타워사거리,학동역5번출구,2023-05-31,08:03:11,3412번(강동공영차고지~강남역),서울74사4220

In [3]:
go_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   탑승 일시   50 non-null     object
 1   탑승 시간   50 non-null     object
 2   교통수단    50 non-null     object
 3   사용처     50 non-null     object
 4   사용금액    50 non-null     object
 5   사용후잔액   50 non-null     object
 6   승차역     50 non-null     object
 7   하차역     50 non-null     object
 8   하차일시    50 non-null     object
 9   하차 시간   50 non-null     object
 10  노선(호선)  50 non-null     object
 11  차량번호    4 non-null      object
dtypes: object(12)
memory usage: 4.8+ KB

In [4]:
leave_data.head()

,탑승 일시,탑승 시간,교통수단,사용처,사용금액,사용후잔액,승차역,하차역,하차일시,하차 시간,노선(호선),차량번호
0,2023-05-31,18:13:29,버스,경남여객(노선입찰제),"1,950원","23,850원",신논현역.주류성빌딩,동원로얄듀크.용인등기소,2023-05-31,19:36:48,경기버스노선,NaN
1,2023-05-31,18:02:14,지하철,서울교통공사,"1,750원","25,800원",학동,신논현,2023-05-31,18:08:17,7호선,NaN
2,2023-05-30,20:33:46,버스,경남여객(노선입찰제),"1,850원","30,750원",신논현역.주류성빌딩,동원로얄듀크.용인등기소,2023-05-30,21:40:09,경기버스노선,NaN
3,2023-05-30,20:15:48,지하철,서울교통공사,"1,750원","32,600원",학동,신논현,2023-05-30,20:27:01,7호선,NaN
4,2023-05-26,18:15:44,버스,경남여객(노선입찰제),"1,850원","37,450원",신논현역.주류성빌딩,동원로얄듀크.용인등기소,2023-05-26,19:31:28,경기버스노선,NaN

In [5]:
go_sort_data = go_data.sort_values(by=['탑승 일시', '탑승 시간'], ascending=[True, True])

In [6]:
go_sort_data.head()

,탑승 일시,탑승 시간,교통수단,사용처,사용금액,사용후잔액,승차역,하차역,하차일시,하차 시간,노선(호선),차량번호
49,2023-04-19,06:54:56,버스,경남여객(노선입찰제),"2,800원","9,950원",명지대입구,신논현역.주류성빌딩,2023-04-19,08:00:49,경기버스노선,NaN
48,2023-04-19,08:06:46,버스,경기상운(노선입찰제),300원,"9,650원",지하철2호선.강남역(중),학동역6번출구,2023-04-19,08:20:23,경기버스노선,NaN
47,2023-04-20,06:45:55,버스,경남여객(노선입찰제),"2,800원","13,750원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-04-20,07:50:04,경기버스노선,NaN
46,2023-04-20,08:06:14,버스,경기상운(노선입찰제),300원,"13,450원",지하철2호선.강남역(중),학동역6번출구,2023-04-20,08:15:44,경기버스노선,NaN
45,2023-04-21,06:42:53,버스,경남여객(노선입찰제),"2,800원","7,550원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-04-21,07:39:46,경기버스노선,NaN

In [7]:
leave_data = leave_data.sort_values(by=['탑승 일시', '탑승 시간'], ascending=[True, True])
leave_data.head()

,탑승 일시,탑승 시간,교통수단,사용처,사용금액,사용후잔액,승차역,하차역,하차일시,하차 시간,노선(호선),차량번호
49,2023-04-19,18:20:08,버스,경기상운(노선입찰제),"2,800원","6,850원",학동역6번출구,뱅뱅사거리(중),2023-04-19,18:56:51,경기버스노선,NaN
48,2023-04-19,19:00:43,버스,경남여객(노선입찰제),300원,"16,550원",뱅뱅사거리(중),동원로얄듀크.용인등기소,2023-04-19,20:04:19,경기버스노선,NaN
47,2023-04-20,20:08:17,버스,경기상운(노선입찰제),"2,800원","10,650원",학동역6번출구,지하철2호선강남역(중),2023-04-20,20:30:22,경기버스노선,NaN
46,2023-04-20,20:31:57,버스,경남여객(노선입찰제),300원,"10,350원",신논현역.주류성빌딩,동원로얄듀크.용인등기소,2023-04-20,21:37:25,경기버스노선,NaN
45,2023-04-26,18:34:34,버스,경기상운(노선입찰제),"2,800원","15,750원",학동역6번출구,지하철2호선강남역(중),2023-04-26,18:51:41,경기버스노선,NaN

In [8]:
leave_data = leave_data.reset_index(drop=True)
leave_data.index += 1
leave_data.head()

,탑승 일시,탑승 시간,교통수단,사용처,사용금액,사용후잔액,승차역,하차역,하차일시,하차 시간,노선(호선),차량번호
1,2023-04-19,18:20:08,버스,경기상운(노선입찰제),"2,800원","6,850원",학동역6번출구,뱅뱅사거리(중),2023-04-19,18:56:51,경기버스노선,NaN
2,2023-04-19,19:00:43,버스,경남여객(노선입찰제),300원,"16,550원",뱅뱅사거리(중),동원로얄듀크.용인등기소,2023-04-19,20:04:19,경기버스노선,NaN
3,2023-04-20,20:08:17,버스,경기상운(노선입찰제),"2,800원","10,650원",학동역6번출구,지하철2호선강남역(중),2023-04-20,20:30:22,경기버스노선,NaN
4,2023-04-20,20:31:57,버스,경남여객(노선입찰제),300원,"10,350원",신논현역.주류성빌딩,동원로얄듀크.용인등기소,2023-04-20,21:37:25,경기버스노선,NaN
5,2023-04-26,18:34:34,버스,경기상운(노선입찰제),"2,800원","15,750원",학동역6번출구,지하철2호선강남역(중),2023-04-26,18:51:41,경기버스노선,NaN

In [9]:
go_sort_data = go_sort_data.reset_index(drop=True)
go_sort_data.index += 1
go_sort_data.head()

,탑승 일시,탑승 시간,교통수단,사용처,사용금액,사용후잔액,승차역,하차역,하차일시,하차 시간,노선(호선),차량번호
1,2023-04-19,06:54:56,버스,경남여객(노선입찰제),"2,800원","9,950원",명지대입구,신논현역.주류성빌딩,2023-04-19,08:00:49,경기버스노선,NaN
2,2023-04-19,08:06:46,버스,경기상운(노선입찰제),300원,"9,650원",지하철2호선.강남역(중),학동역6번출구,2023-04-19,08:20:23,경기버스노선,NaN
3,2023-04-20,06:45:55,버스,경남여객(노선입찰제),"2,800원","13,750원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-04-20,07:50:04,경기버스노선,NaN
4,2023-04-20,08:06:14,버스,경기상운(노선입찰제),300원,"13,450원",지하철2호선.강남역(중),학동역6번출구,2023-04-20,08:15:44,경기버스노선,NaN
5,2023-04-21,06:42:53,버스,경남여객(노선입찰제),"2,800원","7,550원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-04-21,07:39:46,경기버스노선,NaN

In [10]:
go_sort_data = go_sort_data.drop("차량번호", axis=1)
leave_data = leave_data.drop("차량번호", axis=1)

go_sort_data.head()

,탑승 일시,탑승 시간,교통수단,사용처,사용금액,사용후잔액,승차역,하차역,하차일시,하차 시간,노선(호선)
1,2023-04-19,06:54:56,버스,경남여객(노선입찰제),"2,800원","9,950원",명지대입구,신논현역.주류성빌딩,2023-04-19,08:00:49,경기버스노선
2,2023-04-19,08:06:46,버스,경기상운(노선입찰제),300원,"9,650원",지하철2호선.강남역(중),학동역6번출구,2023-04-19,08:20:23,경기버스노선
3,2023-04-20,06:45:55,버스,경남여객(노선입찰제),"2,800원","13,750원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-04-20,07:50:04,경기버스노선
4,2023-04-20,08:06:14,버스,경기상운(노선입찰제),300원,"13,450원",지하철2호선.강남역(중),학동역6번출구,2023-04-20,08:15:44,경기버스노선
5,2023-04-21,06:42:53,버스,경남여객(노선입찰제),"2,800원","7,550원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-04-21,07:39:46,경기버스노선

In [11]:
from datetime import datetime

go_sort_data['탑승 시간'] = pd.to_datetime(go_sort_data['탑승 시간'])
go_sort_data['하차 시간'] = pd.to_datetime(go_sort_data['하차 시간'])

# 하차 시간이 "0시"인 경우 다음 날의 자정으로 처리
go_sort_data.loc[go_sort_data["하차 시간"].dt.hour == 0, "하차 시간"] += pd.DateOffset(days=1)

C:\Users\korea\AppData\Local\Temp\ipykernel_11696\1201688990.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  go_sort_data['탑승 시간'] = pd.to_datetime(go_sort_data['탑승 시간'])
C:\Users\korea\AppData\Local\Temp\ipykernel_11696\1201688990.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  go_sort_data['하차 시간'] = pd.to_datetime(go_sort_data['하차 시간'])

In [12]:
go_sort_data['이동 시간'] = go_sort_data['하차 시간'] - go_sort_data['탑승 시간']
go_sort_data

,탑승 일시,탑승 시간,교통수단,사용처,사용금액,사용후잔액,승차역,하차역,하차일시,하차 시간,노선(호선),이동 시간
1,2023-04-19,2023-06-02 06:54:56,버스,경남여객(노선입찰제),"2,800원","9,950원",명지대입구,신논현역.주류성빌딩,2023-04-19,2023-06-02 08:00:49,경기버스노선,0 days 01:05:53
2,2023-04-19,2023-06-02 08:06:46,버스,경기상운(노선입찰제),300원,"9,650원",지하철2호선.강남역(중),학동역6번출구,2023-04-19,2023-06-02 08:20:23,경기버스노선,0 days 00:13:37
3,2023-04-20,2023-06-02 06:45:55,버스,경남여객(노선입찰제),"2,800원","13,750원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-04-20,2023-06-02 07:50:04,경기버스노선,0 days 01:04:09
4,2023-04-20,2023-06-02 08:06:14,버스,경기상운(노선입찰제),300원,"13,450원",지하철2호선.강남역(중),학동역6번출구,2023-04-20,2023-06-02 08:15:44,경기버스노선,0 days 00:09:30
5,2023-04-21,2023-06-02 06:42:53,버스,경남여객(노선입찰제),"2,800원","7,550원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-04-21,2023-06-02 07:39:46,경기버스노선,0 days 00:56:53
6,2023-04-21,2023-06-02 07:56:17,버스,경기상운(노선입찰제),300원,"7,250원",지하철2호선.강남역(중),학동역6번출구,2023-04-21,2023-06-02 08:07:16,경기버스노선,0 days 00:10:59
7,2023-04-26,2023-06-02 06:39:05,버스,경남여객(노선입찰제),"2,800원","8,950원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-04-26,2023-06-02 07:47:43,경기버스노선,0 days 01:08:38
8,2023-04-26,2023-06-02 07:51:13,버스,경기상운(노선입찰제),400원,"8,550원",지하철2호선.강남역(중),학동역,2023-04-26,2023-06-02 08:02:05,경기버스노선,0 days 00:10:52
9,2023-04-27,2023-06-02 06:54:06,버스,경남여객(노선입찰제),"2,800원","12,550원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-04-27,2023-06-02 08:01:31,경기버스노선,0 days 01:07:25
10,2023-04-27,2023-06-02 08:09:22,버스,경기상운(노선입찰제),400원,"12,150원",지하철2호선.강남역(중),학동역6번출구,2023-04-27,2023-06-02 08:22:56,경기버스노선,0 days 00:13:34
11,2023-04-28,2023-06-02 06:42:44,버스,경남여객(노선입찰제),"2,800원","56,150원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-04-28,2023-06-02 07:37:29,경기버스노선,0 days 00:54:45
12,2023-04-28,2023-06-02 07:54:09,버스,경기상운(노선입찰제),300원,"55,850원",지하철2호선.강남역(중),학동역6번출구,2023-04-28,2023-06-02 08:04:29,경기버스노선,0 days 00:10:20
13,2023-05-02,2023-06-02 06:42:16,버스,경남여객(노선입찰제),"2,800원","49,850원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-05-02,2023-06-02 07:58:56,경기버스노선,0 days 01:16:40
14,2023-05-02,2023-06-02 08:04:45,버스,경기상운(노선입찰제),400원,"49,450원",지하철2호선.강남역(중),학동역6번출구,2023-05-02,2023-06-02 08:17:39,경기버스노선,0 days 00:12:54
15,2023-05-03,2023-06-02 06:39:06,버스,경남여객(노선입찰제),"2,800원","43,450원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-05-03,2023-06-02 07:42:57,경기버스노선,0 days 01:03:51
16,2023-05-03,2023-06-02 08:04:14,버스,경기상운(노선입찰제),400원,"43,050원",지하철2호선.강남역(중),학동역6번출구,2023-05-03,2023-06-02 08:16:05,경기버스노선,0 days 00:11:51
17,2023-05-04,2023-06-02 06:27:07,버스,경남여객(노선입찰제),"2,400원","37,550원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-05-04,2023-06-02 07:28:55,경기버스노선,0 days 01:01:48
18,2023-05-04,2023-06-02 07:32:25,버스,경기상운(노선입찰제),400원,"37,150원",지하철2호선.강남역(중),학동역6번출구,2023-05-04,2023-06-02 07:43:27,경기버스노선,0 days 00:11:02
19,2023-05-08,2023-06-02 06:39:24,버스,경남여객(노선입찰제),"2,800원","31,150원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-05-08,2023-06-02 07:53:32,경기버스노선,0 days 01:14:08
20,2023-05-08,2023-06-02 08:09:35,버스,경기상운(노선입찰제),400원,"30,750원",지하철2호선.강남역(중),학동역6번출구,2023-05-08,2023-06-02 08:23:03,경기버스노선,0 days 00:13:28
21,2023-05-09,2023-06-02 06:42:51,버스,경남여객(노선입찰제),"2,800원","24,850원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-05-09,2023-06-02 07:47:55,경기버스노선,0 days 01:05:04
22,2023-05-09,2023-06-02 07:58:42,버스,경기상운(노선입찰제),300원,"24,550원",지하철2호선.강남역(중),학동역6번출구,2023-05-09,2023-06-02 08:09:52,경기버스노선,0 days 00:11:10
23,2023-05-10,2023-06-02 06:45:36,버스,경남여객(노선입찰제),"2,800원","18,650원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-05-10,2023-06-02 07:41:51,경기버스노선,0 days 00:56:15
24,2023-05-10,2023-06-02 07:56:02,버스,경기상운(노선입찰제),300원,"18,350원",지하철2호선.강남역(중),학동역6번출구,2023-05-10,2023-06-02 08:07:30,경기버스노선,0 days 00:11:28
25,2023-05-11,2023-06-02 06:42:56,버스,경남여객(노선입찰제),"2,800원","12,350원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-05-11,2023-06-02 07:40:22,경기버스노선,0 days 00:57:26
26,2023-05-11,2023-06-02 07:55:57,버스,경기상운(노선입찰제),300원,"12,050원",지하철2호선.강남역(중),학동역6번출구,2023-05-11,2023-06-02 08:07:14,경기버스노선,0 days 00:11:17
27,2023-05-12,2023-06-02 06:39:25,버스,경남여객(노선입찰제),"2,800원","56,150원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-05-12,2023-06-02 07:44:48,경기버스노선,0 days 01:05:23
28,2023-05-12,2023-06-02 08:00:54,버스,경기상운(노선입찰제),400원,"55,750원",지하철2호선.강남역(중),학동역6번출구,2023-05-12,2023-06-02 08:10:05,경기버스노선,0 days 00:09:11
29,2023-05-15,2023-06-02 06:36:33,버스,경남여객(노선입찰제),"2,800원","49,850원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-05-15,2023-06-02 07:45:40,경기버스노선,0 days 01:09:07
30,2023-05-15,2023-06-02 07:59:00,버스,경기상운(노선입찰제),300원,"49,550원",지하철2호선.강남역(중),학동역6번출구,2023-05-15,2023-06-02 08:10:13,경기버스노선,0 days 00:11:13
31,2023-05-16,2023-06-02 06:27:06,버스,경남여객(노선입찰제),"2,400원","43,550원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-05-16,2023-06-02 07:26:33,경기버스노선,0 days 00:59:27
32,2023-05-16,2023-06-02 07:39:54,버스,경기상운(노선입찰제),400원,"43,150원",지하철2호선.강남역(중),학동역6번출구,2023-05-16,2023-06-02 07:52:04,경기버스노선,0 days 00:12:10
33,2023-05-17,2023-06-02 06:39:02,버스,경남여객(노선입찰제),"2,800원","36,900원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-05-17,2023-06-02 07:40:11,경기버스노선,0 days 01:01:09
34,2023-05-17,2023-06-02 07:53:26,버스,경기상운(노선입찰제),400원,"36,500원",지하철2호선.강남역(중),학동역6번출구,2023-05-17,2023-06-02 08:07:01,경기버스노선,0 days 00:13:35
35,2023-05-18,2023-06-02 06:39:11,버스,경남여객(노선입찰제),"2,800원","30,000원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-05-18,2023-06-02 07:41:25,경기버스노선,0 days 01:02:14
36,2023-05-18,2023-06-02 07:50:52,버스,경기상운(노선입찰제),400원,"29,600원",지하철2호선.강남역(중),학동역6번출구,2023-05-18,2023-06-02 08:01:48,경기버스노선,0 days 00:10:56
37,2023-05-19,2023-06-02 06:36:47,버스,경남여객(노선입찰제),"2,800원","23,100원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-05-19,2023-06-02 07:39:55,경기버스노선,0 days 01:03:08
38,2023-05-19,2023-06-02 07:58:35,버스,(주)서울승합,300원,"22,800원",신논현역.구교보타워사거리,학동역5번출구,2023-05-19,2023-06-02 08:05:17,3412번(강동공영차고지~강남역),0 days 00:06:42
39,2023-05-22,2023-06-02 06:33:31,버스,경남여객(노선입찰제),"2,800원","16,400원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-05-22,2023-06-02 07:43:06,경기버스노선,0 days 01:09:35
40,2023-05-22,2023-06-02 07:53:03,버스,경기상운(노선입찰제),300원,"16,100원",지하철2호선.강남역(중),학동역,2023-05-22,2023-06-02 08:02:43,경기버스노선,0 days 00:09:40
41,2023-05-23,2023-06-02 06:39:11,버스,경남여객(노선입찰제),"2,800원","59,600원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-05-23,2023-06-02 07:38:00,경기버스노선,0 days 00:58:49
42,2023-05-23,2023-06-02 07:42:17,버스,(주)서울승합,400원,"59,200원",신논현역.구교보타워사거리,학동역5번출구,2023-05-23,2023-06-02 07:50:37,3412번(강동공영차고지~강남역),0 days 00:08:20
43,2023-05-30,2023-06-02 06:36:58,버스,경남여객(노선입찰제),"2,800원","34,650원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-05-30,2023-06-02 07:45:09,경기버스노선,0 days 01:08:11
44,2023-05-30,2023-06-02 06:36:58,버스,경남여객(노선입찰제),"2,800원","34,650원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-05-30,2023-06-02 07:45:09,경기버스노선,0 days 01:08:11
45,2023-05-30,2023-06-02 07:52:41,버스,경기상운(노선입찰제),300원,"34,350원",지하철2호선.강남역(중),학동역6번출구,2023-05-30,2023-06-02 08:05:21,경기버스노선,0 days 00:12:40
46,2023-05-30,2023-06-02 07:52:41,버스,경기상운(노선입찰제),300원,"34,350원",지하철2호선.강남역(중),학동역6번출구,2023-05-30,2023-06-02 08:05:21,경기버스노선,0 days 00:12:40
47,2023-05-31,2023-06-02 06:51:06,버스,경남여객(노선입찰제),"2,800원","27,950원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-05-31,2023-06-02 07:53:30,경기버스노선,0 days 01:02:24
48,2023-05-31,2023-06-02 06:51:06,버스,경남여객(노선입찰제),"2,800원","27,950원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-05-31,2023-06-02 07:53:30,경기버스노선,0 days 01:02:24
49,2023-05-31,2023-06-02 07:56:26,버스,(주)서울승합,400원,"27,550원",신논현역.구교보타워사거리,학동역5번출구,2023-05-31,2023-06-02 08:03:11,3412번(강동공영차고지~강남역),0 days 00:06:45
50,2023-05-31,2023-06-02 07:56:26,버스,(주)서울승합,400원,"27,550원",신논현역.구교보타워사거리,학동역5번출구,2023-05-31,2023-06-02 08:03:11,3412번(강동공영차고지~강남역),0 days 00:06:45

In [13]:
go_sort_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 1 to 50
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   탑승 일시   50 non-null     object
 1   탑승 시간   50 non-null     datetime64[ns]
 2   교통수단    50 non-null     object
 3   사용처     50 non-null     object
 4   사용금액    50 non-null     object
 5   사용후잔액   50 non-null     object
 6   승차역     50 non-null     object
 7   하차역     50 non-null     object
 8   하차일시    50 non-null     object
 9   하차 시간   50 non-null     datetime64[ns]
 10  노선(호선)  50 non-null     object
 11  이동 시간   50 non-null     timedelta64[ns]
dtypes: datetime64[ns](2), object(9), timedelta64[ns](1)
memory usage: 4.8+ KB

In [14]:
duplicates = go_sort_data[go_sort_data.duplicated()]
print(duplicates)

         탑승 일시               탑승 시간 교통수단          사용처    사용금액    사용후잔액
44  2023-05-30 2023-06-02 06:36:58   버스  경남여객(노선입찰제)  2,800원  34,650원  \
46  2023-05-30 2023-06-02 07:52:41   버스  경기상운(노선입찰제)    300원  34,350원
48  2023-05-31 2023-06-02 06:51:06   버스  경남여객(노선입찰제)  2,800원  27,950원
50  2023-05-31 2023-06-02 07:56:26   버스      (주)서울승합    400원  27,550원

              승차역         하차역        하차일시               하차 시간
44   동원로얄듀크.용인등기소  신논현역.주류성빌딩  2023-05-30 2023-06-02 07:45:09  \
46  지하철2호선.강남역(중)     학동역6번출구  2023-05-30 2023-06-02 08:05:21
48   동원로얄듀크.용인등기소  신논현역.주류성빌딩  2023-05-31 2023-06-02 07:53:30
50  신논현역.구교보타워사거리     학동역5번출구  2023-05-31 2023-06-02 08:03:11

                노선(호선)           이동 시간
44              경기버스노선 0 days 01:08:11
46              경기버스노선 0 days 00:12:40
48              경기버스노선 0 days 01:02:24
50  3412번(강동공영차고지~강남역) 0 days 00:06:45

In [15]:
go_sort_data = go_sort_data.drop_duplicates()
go_sort_data

,탑승 일시,탑승 시간,교통수단,사용처,사용금액,사용후잔액,승차역,하차역,하차일시,하차 시간,노선(호선),이동 시간
1,2023-04-19,2023-06-02 06:54:56,버스,경남여객(노선입찰제),"2,800원","9,950원",명지대입구,신논현역.주류성빌딩,2023-04-19,2023-06-02 08:00:49,경기버스노선,0 days 01:05:53
2,2023-04-19,2023-06-02 08:06:46,버스,경기상운(노선입찰제),300원,"9,650원",지하철2호선.강남역(중),학동역6번출구,2023-04-19,2023-06-02 08:20:23,경기버스노선,0 days 00:13:37
3,2023-04-20,2023-06-02 06:45:55,버스,경남여객(노선입찰제),"2,800원","13,750원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-04-20,2023-06-02 07:50:04,경기버스노선,0 days 01:04:09
4,2023-04-20,2023-06-02 08:06:14,버스,경기상운(노선입찰제),300원,"13,450원",지하철2호선.강남역(중),학동역6번출구,2023-04-20,2023-06-02 08:15:44,경기버스노선,0 days 00:09:30
5,2023-04-21,2023-06-02 06:42:53,버스,경남여객(노선입찰제),"2,800원","7,550원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-04-21,2023-06-02 07:39:46,경기버스노선,0 days 00:56:53
6,2023-04-21,2023-06-02 07:56:17,버스,경기상운(노선입찰제),300원,"7,250원",지하철2호선.강남역(중),학동역6번출구,2023-04-21,2023-06-02 08:07:16,경기버스노선,0 days 00:10:59
7,2023-04-26,2023-06-02 06:39:05,버스,경남여객(노선입찰제),"2,800원","8,950원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-04-26,2023-06-02 07:47:43,경기버스노선,0 days 01:08:38
8,2023-04-26,2023-06-02 07:51:13,버스,경기상운(노선입찰제),400원,"8,550원",지하철2호선.강남역(중),학동역,2023-04-26,2023-06-02 08:02:05,경기버스노선,0 days 00:10:52
9,2023-04-27,2023-06-02 06:54:06,버스,경남여객(노선입찰제),"2,800원","12,550원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-04-27,2023-06-02 08:01:31,경기버스노선,0 days 01:07:25
10,2023-04-27,2023-06-02 08:09:22,버스,경기상운(노선입찰제),400원,"12,150원",지하철2호선.강남역(중),학동역6번출구,2023-04-27,2023-06-02 08:22:56,경기버스노선,0 days 00:13:34
11,2023-04-28,2023-06-02 06:42:44,버스,경남여객(노선입찰제),"2,800원","56,150원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-04-28,2023-06-02 07:37:29,경기버스노선,0 days 00:54:45
12,2023-04-28,2023-06-02 07:54:09,버스,경기상운(노선입찰제),300원,"55,850원",지하철2호선.강남역(중),학동역6번출구,2023-04-28,2023-06-02 08:04:29,경기버스노선,0 days 00:10:20
13,2023-05-02,2023-06-02 06:42:16,버스,경남여객(노선입찰제),"2,800원","49,850원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-05-02,2023-06-02 07:58:56,경기버스노선,0 days 01:16:40
14,2023-05-02,2023-06-02 08:04:45,버스,경기상운(노선입찰제),400원,"49,450원",지하철2호선.강남역(중),학동역6번출구,2023-05-02,2023-06-02 08:17:39,경기버스노선,0 days 00:12:54
15,2023-05-03,2023-06-02 06:39:06,버스,경남여객(노선입찰제),"2,800원","43,450원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-05-03,2023-06-02 07:42:57,경기버스노선,0 days 01:03:51
16,2023-05-03,2023-06-02 08:04:14,버스,경기상운(노선입찰제),400원,"43,050원",지하철2호선.강남역(중),학동역6번출구,2023-05-03,2023-06-02 08:16:05,경기버스노선,0 days 00:11:51
17,2023-05-04,2023-06-02 06:27:07,버스,경남여객(노선입찰제),"2,400원","37,550원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-05-04,2023-06-02 07:28:55,경기버스노선,0 days 01:01:48
18,2023-05-04,2023-06-02 07:32:25,버스,경기상운(노선입찰제),400원,"37,150원",지하철2호선.강남역(중),학동역6번출구,2023-05-04,2023-06-02 07:43:27,경기버스노선,0 days 00:11:02
19,2023-05-08,2023-06-02 06:39:24,버스,경남여객(노선입찰제),"2,800원","31,150원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-05-08,2023-06-02 07:53:32,경기버스노선,0 days 01:14:08
20,2023-05-08,2023-06-02 08:09:35,버스,경기상운(노선입찰제),400원,"30,750원",지하철2호선.강남역(중),학동역6번출구,2023-05-08,2023-06-02 08:23:03,경기버스노선,0 days 00:13:28
21,2023-05-09,2023-06-02 06:42:51,버스,경남여객(노선입찰제),"2,800원","24,850원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-05-09,2023-06-02 07:47:55,경기버스노선,0 days 01:05:04
22,2023-05-09,2023-06-02 07:58:42,버스,경기상운(노선입찰제),300원,"24,550원",지하철2호선.강남역(중),학동역6번출구,2023-05-09,2023-06-02 08:09:52,경기버스노선,0 days 00:11:10
23,2023-05-10,2023-06-02 06:45:36,버스,경남여객(노선입찰제),"2,800원","18,650원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-05-10,2023-06-02 07:41:51,경기버스노선,0 days 00:56:15
24,2023-05-10,2023-06-02 07:56:02,버스,경기상운(노선입찰제),300원,"18,350원",지하철2호선.강남역(중),학동역6번출구,2023-05-10,2023-06-02 08:07:30,경기버스노선,0 days 00:11:28
25,2023-05-11,2023-06-02 06:42:56,버스,경남여객(노선입찰제),"2,800원","12,350원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-05-11,2023-06-02 07:40:22,경기버스노선,0 days 00:57:26
26,2023-05-11,2023-06-02 07:55:57,버스,경기상운(노선입찰제),300원,"12,050원",지하철2호선.강남역(중),학동역6번출구,2023-05-11,2023-06-02 08:07:14,경기버스노선,0 days 00:11:17
27,2023-05-12,2023-06-02 06:39:25,버스,경남여객(노선입찰제),"2,800원","56,150원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-05-12,2023-06-02 07:44:48,경기버스노선,0 days 01:05:23
28,2023-05-12,2023-06-02 08:00:54,버스,경기상운(노선입찰제),400원,"55,750원",지하철2호선.강남역(중),학동역6번출구,2023-05-12,2023-06-02 08:10:05,경기버스노선,0 days 00:09:11
29,2023-05-15,2023-06-02 06:36:33,버스,경남여객(노선입찰제),"2,800원","49,850원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-05-15,2023-06-02 07:45:40,경기버스노선,0 days 01:09:07
30,2023-05-15,2023-06-02 07:59:00,버스,경기상운(노선입찰제),300원,"49,550원",지하철2호선.강남역(중),학동역6번출구,2023-05-15,2023-06-02 08:10:13,경기버스노선,0 days 00:11:13
31,2023-05-16,2023-06-02 06:27:06,버스,경남여객(노선입찰제),"2,400원","43,550원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-05-16,2023-06-02 07:26:33,경기버스노선,0 days 00:59:27
32,2023-05-16,2023-06-02 07:39:54,버스,경기상운(노선입찰제),400원,"43,150원",지하철2호선.강남역(중),학동역6번출구,2023-05-16,2023-06-02 07:52:04,경기버스노선,0 days 00:12:10
33,2023-05-17,2023-06-02 06:39:02,버스,경남여객(노선입찰제),"2,800원","36,900원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-05-17,2023-06-02 07:40:11,경기버스노선,0 days 01:01:09
34,2023-05-17,2023-06-02 07:53:26,버스,경기상운(노선입찰제),400원,"36,500원",지하철2호선.강남역(중),학동역6번출구,2023-05-17,2023-06-02 08:07:01,경기버스노선,0 days 00:13:35
35,2023-05-18,2023-06-02 06:39:11,버스,경남여객(노선입찰제),"2,800원","30,000원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-05-18,2023-06-02 07:41:25,경기버스노선,0 days 01:02:14
36,2023-05-18,2023-06-02 07:50:52,버스,경기상운(노선입찰제),400원,"29,600원",지하철2호선.강남역(중),학동역6번출구,2023-05-18,2023-06-02 08:01:48,경기버스노선,0 days 00:10:56
37,2023-05-19,2023-06-02 06:36:47,버스,경남여객(노선입찰제),"2,800원","23,100원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-05-19,2023-06-02 07:39:55,경기버스노선,0 days 01:03:08
38,2023-05-19,2023-06-02 07:58:35,버스,(주)서울승합,300원,"22,800원",신논현역.구교보타워사거리,학동역5번출구,2023-05-19,2023-06-02 08:05:17,3412번(강동공영차고지~강남역),0 days 00:06:42
39,2023-05-22,2023-06-02 06:33:31,버스,경남여객(노선입찰제),"2,800원","16,400원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-05-22,2023-06-02 07:43:06,경기버스노선,0 days 01:09:35
40,2023-05-22,2023-06-02 07:53:03,버스,경기상운(노선입찰제),300원,"16,100원",지하철2호선.강남역(중),학동역,2023-05-22,2023-06-02 08:02:43,경기버스노선,0 days 00:09:40
41,2023-05-23,2023-06-02 06:39:11,버스,경남여객(노선입찰제),"2,800원","59,600원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-05-23,2023-06-02 07:38:00,경기버스노선,0 days 00:58:49
42,2023-05-23,2023-06-02 07:42:17,버스,(주)서울승합,400원,"59,200원",신논현역.구교보타워사거리,학동역5번출구,2023-05-23,2023-06-02 07:50:37,3412번(강동공영차고지~강남역),0 days 00:08:20
43,2023-05-30,2023-06-02 06:36:58,버스,경남여객(노선입찰제),"2,800원","34,650원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-05-30,2023-06-02 07:45:09,경기버스노선,0 days 01:08:11
45,2023-05-30,2023-06-02 07:52:41,버스,경기상운(노선입찰제),300원,"34,350원",지하철2호선.강남역(중),학동역6번출구,2023-05-30,2023-06-02 08:05:21,경기버스노선,0 days 00:12:40
47,2023-05-31,2023-06-02 06:51:06,버스,경남여객(노선입찰제),"2,800원","27,950원",동원로얄듀크.용인등기소,신논현역.주류성빌딩,2023-05-31,2023-06-02 07:53:30,경기버스노선,0 days 01:02:24
49,2023-05-31,2023-06-02 07:56:26,버스,(주)서울승합,400원,"27,550원",신논현역.구교보타워사거리,학동역5번출구,2023-05-31,2023-06-02 08:03:11,3412번(강동공영차고지~강남역),0 days 00:06:45

In [16]:
go_sort_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 46 entries, 1 to 49
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   탑승 일시   46 non-null     object
 1   탑승 시간   46 non-null     datetime64[ns]
 2   교통수단    46 non-null     object
 3   사용처     46 non-null     object
 4   사용금액    46 non-null     object
 5   사용후잔액   46 non-null     object
 6   승차역     46 non-null     object
 7   하차역     46 non-null     object
 8   하차일시    46 non-null     object
 9   하차 시간   46 non-null     datetime64[ns]
 10  노선(호선)  46 non-null     object
 11  이동 시간   46 non-null     timedelta64[ns]
dtypes: datetime64[ns](2), object(9), timedelta64[ns](1)
memory usage: 4.7+ KB